export const hook522 = {
  "c01": {
    "result": "A",
    "tests": [[
      "Smooth, easy and constant rising",
      "A",
      "Smooth, easy and constant rising",
      "A",
    ], ["No", "A", "No", "A"]],
  },
  "c02": { "result": "A", "tests": [["No", "A", "No", "A"]] },
  "c03": {
    "result": "A",
    "tests": [["Yes", "A", "Yes", "A"], ["Yes", "A", "Yes", "A"], [
      "Less than 25 km/h",
      "A",
      "Less than 25 km/h",
      "A",
    ]],
  },
  "c04": {
    "result": "A",
    "tests": [["Increasing / greater than 55 cm", "A", "not available", "0"], [
      "not available",
      "0",
      "Increasing / greater than 60 cm",
      "A",
    ], ["not available", "0", "not available", "0"]],
  },
  "c05": {
    "result": "A",
    "tests": [[
      "Dive forward less than 30°",
      "A",
      "Dive forward less than 30°",
      "A",
    ], ["No", "A", "No", "A"]],
  },
  "c06": { "result": "A", "tests": [["No", "A", "No", "A"]] },
  "c07": { "result": "A", "tests": [["Reducing", "A", "Reducing", "A"]] },
  "c08": {
    "result": "A",
    "tests": [["Spontaneous exit", "A", "Spontaneous exit", "A"]],
  },
  "c09": {
    "result": "B",
    "tests": [
      [
        "Immediate reduction of rate of turn",
        "A",
        "Immediate reduction of rate of turn",
        "A",
      ],
      [
        "Spontaneous exit (g force A decreasing, rate of turn decreasing)",
        "A",
        "Spontaneous exit (g force A decreasing, rate of turn decreasing)",
        "A",
      ],
      [
        "720° to 1 080°, spontaneous recovery",
        "B",
        "Less than 720°, spontaneous ecovery",
        "A",
      ],
    ],
  },
  "c10": {
    "result": "A",
    "tests": [
      ["Rocking back less than 45°", "A", "Rocking back less than 45°", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      [
        "Dive forward 0° to 30° Keeping course",
        "A",
        "Dive forward 0° to 30° Keeping course",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["Rocking back less than 45°", "A", "Rocking back less than 45°", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      [
        "Dive forward 0° to 30° Keeping course",
        "A",
        "Dive forward 0° to 30° Keeping course",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["Rocking back less than 45°", "A", "Rocking back less than 45°", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      [
        "Dive forward 0° to 30° Keeping course",
        "A",
        "Dive forward 0° to 30° Keeping course",
        "A",
      ],
      ["No", "A", "No", "A"],
    ],
  },
  "c11": {
    "result": "A",
    "tests": [
      ["Yes", "A", "Yes", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      [
        "Changing course less than 45°",
        "A",
        "Changing course less than 45°",
        "A",
      ],
      ["No", "A", "No", "A"],
    ],
  },
  "c12": {
    "result": "A",
    "tests": [[
      "Spontaneous in less than 3 s",
      "A",
      "Spontaneous in less than 3 s",
      "A",
    ], ["No", "A", "No", "A"]],
  },
  "c13": {
    "result": "A",
    "tests": [
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      ["No collapse", "A", "No collapse", "A"],
      ["No", "A", "No", "A"],
      ["Less than 45°", "A", "Less than 45°", "A"],
      ["Most lines tight", "A", "Most lines tight", "A"],
    ],
  },
  "c14": {
    "result": "A",
    "tests": [
      [
        "Less than 90° / Dive or roll angle 0° to 15°",
        "A",
        "Less than 90° / Dive or roll angle A 0° to 15°",
        "A",
      ],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      [
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
      [
        "Less than 90° / Dive or roll angle 15° to 45°",
        "A",
        "Less than 90° / Dive or roll angle 15° to 45°",
        "A",
      ],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      [
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
      [
        "Less than 90° / Dive or roll angle 0° to 15°",
        "A",
        "Less than 90° / Dive or roll angle 0° to 15°",
        "A",
      ],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      [
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
      [
        "Less than 90° / Dive or roll angle 15° to 45°",
        "A",
        "Less than 90° / Dive or roll angle 15° to 45°",
        "A",
      ],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      [
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
        "No (or only a small number of collapsed cells with a spontaneous reinflation)",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
    ],
  },
  "c15": {
    "result": "A",
    "tests": [["Yes", "A", "Yes", "A"], ["Yes", "A", "Yes", "A"], [
      "More than 50 % of the symmetric control travel",
      "A",
      "More than 50 % of the symmetric control travel",
      "A",
    ]],
  },
  "c16": { "result": "A", "tests": [["No", "A", "No", "A"]] },
  "c17": { "result": "A", "tests": [["No", "A", "No", "A"]] },
  "c18": {
    "result": "A",
    "tests": [[
      "Stops spinning in less than 90°",
      "A",
      "Stops spinning in less than 90°",
      "A",
    ], ["No", "A", "No", "A"]],
  },
  "c19": {
    "result": "A",
    "tests": [
      [
        "Changing course less than 45°",
        "A",
        "Changing course less than 45°",
        "A",
      ],
      [
        "Remains stable with straight span",
        "A",
        "Remains stable with straight span",
        "A",
      ],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      ["No", "A", "No", "A"],
    ],
  },
  "c20": {
    "result": "A",
    "tests": [
      ["Dedicated controls", "A", "Dedicated controls", "A"],
      ["Stable flight", "A", "Stable flight", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
    ],
  },
  "c21": {
    "result": "B",
    "tests": [
      ["Dedicated controls", "A", "Dedicated controls", "A"],
      ["Stable flight", "A", "Stable flight", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Recovery through pilot action in B less than a further 3 s",
        "B",
      ],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      ["Stable flight", "A", "Stable flight", "A"],
    ],
  },
  "c22": {
    "result": "A",
    "tests": [["Yes", "A", "Yes", "A"], ["No", "A", "No", "A"]],
  },
  "c23": {
    "result": "0",
    "tests": [["not available", "0", "not available", "0"], [
      "not available",
      "0",
      "not available",
      "0",
    ], ["not available", "0", "not available", "0"]],
  },
  "classification": "B",
  "folding_lines_used": "no",
  "glider_model": "Hook 5 22",
};
