export const soarxs = {
  "c01": {
    "result": "A",
    "tests": [[
      "ooth, easy and constant rising",
      "A Smooth, easy and constant rising",
      "A",
      "TODO",
    ], ["No", "A", "No", "A"]],
  },
  "c02": { "result": "A", "tests": [["No", "A", "No", "A"]] },
  "c03": {
    "result": "A",
    "tests": [["Yes", "A", "Yes", "A"], ["Yes", "A", "Yes", "A"], [
      "Less than 25 km/h",
      "A",
      "Less than 25 km/h",
      "A",
    ]],
  },
  "c04": {
    "result": "A",
    "tests": [
      [
        "Increasing / greater than 55 cm",
        "A",
        "Increasing / greater than 55 cm",
        "A",
      ],
      ["not available", "0", "not available", "0"],
      ["not available", "0", "not available", "0"],
    ],
  },
  "c05": {
    "result": "A",
    "tests": [[
      "Dive forward less than 30°",
      "A",
      "Dive forward less than 30°",
      "A",
    ], ["No", "A", "No", "A"]],
  },
  "c06": { "result": "TODO", "tests": [["No", "A", "No", "A"]] },
  "c07": { "result": "A", "tests": [["Reducing", "A", "Reducing", "A"]] },
  "c08": {
    "result": "A",
    "tests": [["Spontaneous exit", "A", "Spontaneous exit", "A"]],
  },
  "c09": {
    "result": "A",
    "tests": [
      [
        "Immediate reduction of rate of turn",
        "A",
        "Immediate reduction of rate of turn",
        "A",
      ],
      ["Spontaneous exit", "A", "Spontaneous exit", "A"],
      [
        "Less than 720°, spontaneous",
        "A",
        "Less than 720°, spontaneous\nrecovery",
        "A",
      ],
    ],
  },
  "c10": {
    "result": "B",
    "tests": [
      ["Rocking back less than 45°", "A", "Rocking back less than 45°", "A"],
      ["Spontaneous in 3 s to 5 s", "B", "Spontaneous in less than 3 s", "A"],
      [
        "Dive forward 0° to 30° Keeping",
        "A",
        "Dive forward 0° to 30° Keeping\ncourse",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["Rocking back less than 45°", "A", "Rocking back less than 45°", "A"],
      ["Spontaneous in 3 s to 5 s", "B", "Spontaneous in less than 3 s", "A"],
      [
        "Dive forward 0° to 30° / Keeping",
        "A",
        "Dive forward 0° to 30° / Keeping\ncourse",
        "A",
      ],
      ["No", "A", "No", "A"],
      ["Rocking back less than 45°", "A", "Rocking back less than 45°", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      [
        "Dive forward 0° to 30° / Keeping",
        "A",
        "Dive forward 0° to 30° / Keeping\ncourse",
        "A",
      ],
      ["No", "A", "No", "A"],
    ],
  },
  "c11": {
    "result": "A",
    "tests": [
      ["Yes", "A", "Yes", "A"],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      [
        "Changing course less than 45°",
        "A",
        "Changing course less than 45°",
        "A",
      ],
      ["No", "A", "No", "A"],
    ],
  },
  "c12": {
    "result": "A",
    "tests": [[
      "Spontaneous in less than 3 s",
      "A",
      "Spontaneous in less than 3 s",
      "A",
    ], ["No", "A", "No", "A"]],
  },
  "c13": {
    "result": "A",
    "tests": [
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      ["No collapse", "A", "No collapse", "A"],
      ["No", "A", "No", "A"],
      ["Less than 45°", "A", "Less than 45°", "A"],
      ["Most lines tight", "A", "Most lines tight", "A"],
    ],
  },
  "c14": {
    "result": "B",
    "tests": [
      ["TODO", "TODO", "TODO", "TODO"],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["Spontaneous re-inflation", "A", "Spontaneous re-inflation", "A"],
      ["Less than 360°", "A", "Less than 360°", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["No", "A", "No", "A"],
      ["No", "A", "No", "A"],
    ],
  },
  "c15": {
    "result": "TODO",
    "tests": [["Yes", "A", "Yes", "A"], ["Yes", "A", "Yes", "A"], [
      "TODO",
      "TODO",
      "TODO",
      "TODO",
    ]],
  },
  "c16": { "result": "A", "tests": [["No", "A", "No", "A"]] },
  "c17": { "result": "A", "tests": [["No", "A", "No", "A"]] },
  "c18": {
    "result": "B",
    "tests": [[
      "Stops spinning in less than 90°",
      "A",
      "Stops spinning in 90° to 180°",
      "B",
    ], ["No", "A", "No", "A"]],
  },
  "c19": {
    "result": "A",
    "tests": [
      [
        "Changing course less than 45°",
        "A",
        "Changing course less than 45°",
        "A",
      ],
      [
        "Remains stable with straight span",
        "A",
        "Remains stable with straight span",
        "A",
      ],
      [
        "Spontaneous in less than 3 s",
        "A",
        "Spontaneous in less than 3 s",
        "A",
      ],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      ["No", "A", "No", "A"],
    ],
  },
  "c20": {
    "result": "A",
    "tests": [
      ["Dedicated controls", "A", "Dedicated controls", "A"],
      ["Stable flight", "A", "Stable flight", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
    ],
  },
  "c21": {
    "result": "A",
    "tests": [
      ["Dedicated controls", "A", "Dedicated controls", "A"],
      ["Stable flight", "A", "Stable flight", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
      ["Dive forward 0° to 30°", "A", "Dive forward 0° to 30°", "A"],
      ["TODO", "TODO", "TODO", "TODO"],
    ],
  },
  "c22": {
    "result": "A",
    "tests": [["Yes", "A", "Yes", "A"], ["No", "A", "No", "A"]],
  },
  "c23": {
    "result": "TODO",
    "tests": [["not available", "0", "", "not available"], [
      "not available",
      "0",
      "",
      "not available",
    ], ["No", "A", "No", "A"]],
  },
  "classification": "B",
  "folding_lines_used": "no",
  "glider_model": "Soar XS",
};
